language: scala
scala:
- 2.9.2
jdk:
- openjdk7
- oraclejdk7

services:
- mongodb

env:
- PLAY_VERSION=2.0.4

before_script:
- wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
-&nbsp; sbt test

notifications:
email: false